name: Update Google Analytics

on: 
  push:
    branches:
      - master
  schedule:
    - cron:  '5 */8 * * *'
    
jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: swamidass/google-analytics

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update
        run: |
          python3 update_analytics.py 
          git config --global user.email "no-reply@peacefulscience.org"
          git config --global user.name "GitHub Action"          
          git add mostread.json trending.json 
          git commit -m "automated updated by github workflow"
          git push
        env: 
          GA_SERVICE: ${{ secrets.GA_SERVICE }}  
      
