name: Update Google Analytics

on: 
  push:
    branches:
      - master
  schedule:
    - cron:  '5 */6 * * *'
    
job:
  update:
    runs-on: ubuntu-latest
    container:
      image: swamidass/google-analytics
    env: # Or as an environment variable
      GA_SERVICE: ${{ secrets.GA_SERVICE }}
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - run: |
        python3 update_analytics.py
        git add mostread.json trending.json
        git commit -m "automated updated by github workflow"
        git push